### PR TITLE
Make a website

### PR DESCRIPTION
**Pull request by bcomnes**

### CODE REVIEW

**Comment by ungoldman** [comment]
why http://entypo.netlify.com instead of somewhere on https://www.hypermodul.es? kind of makes it seem like it's a netlify project

**Comment by bcomnes** [comment]
I have it set up as entypo.hypermodul.es but my DNS is being slow to update.  I'll switch it over once the DNS goes live.

**Comment by bcomnes** [comment]
I'm going to explore setting up mounted websites as well. e.g. http://www.hypermodul.es/entypo

**Comment by ungoldman** [comment]
👍

**Pull request merged**
