### PR TITLE
Include icon sources in the npm package

### PR DESCRIPTION
**Pull request by jacobwgillespie**
It would be nice if the icon sources (the SVG files) were themselves included in the published NPM package - this allows the icons to be used in applications individually or in other formats (like React components), rather than only as a SVG sprite.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Hey, friendly ping @bcomnes ❤️

**Comment by bcomnes** [comment]
Oh yeah sorry missed this. Yeah this is fine. Will take a look.

**Comment by bcomnes** [comment]
entypo@2.2.0

**Comment by jacobwgillespie** [comment]
Thank you, much appreciated 👍

**Pull request merged**
